//tealium universal tag - utag.25 ut4.0.202604290827, Copyright 2026 Tealium.com Inc. All Rights Reserved.
window.criteo_q=window.criteo_q||[];try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<41){u.loader=function(o,a,b,c,l,m){utag.DB(o);a=document;if(o.type=="iframe"){m=a.getElementById(o.id);if(m&&m.tagName=="IFRAME"){b=m;}else{b=a.createElement("iframe");}o.attrs=o.attrs||{};utag.ut.merge(o.attrs,{"height":"1","width":"1","style":"display:none"},0);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";}if(o.id){b.id=o.id;}for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState=="complete"||this.readyState=="loaded"){this.onreadystatechange=null;o.cb();}};}}if(o.type!="img"&&!m){l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}}};}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.isEmptyObject=function(o,a){for(a in o){if(u.hasOwn(o,a)){return false;}}return true;};u.isEmpty=function(o){var t=u.typeOf(o);if(t=="number"){return isNaN(o);}else if(t=="boolean"){return false;}else if(t=="string"){return o.length===0;}else return u.isEmptyObject(o);};u.arrayUnique=function(array){var a=array.concat();for(var i=0;i<a.length;++i){for(var j=i+1;j<a.length;++j){if(a[i]===a[j])a.splice(j--,1);}}return a;};u.ev={"view":1,"link":1};u.initialized=false;u.scriptRequested=false;u.prep=function(value,alwaysConvert){if(u.typeOf(value)==="string"&&(alwaysConvert||value.indexOf(",")>0)){value=value.replace(/^\s*|\s*$/g,"").split(/\s*,\s*/);}
return value;};u.map_func=function(arr,obj,item){var i=arr.shift();obj[i]=obj[i]||{};if(arr.length>0){u.map_func(arr,obj[i],item);}else{obj[i]=item;}};u.clearEmptyKeys=function(object){for(var key in object){if(object[key]===""||object[key]===undefined){delete object[key];}}
return object;};u.copy_ecm_array=function(sourceObj,sourceProp,destObj,destProp){if(!(destObj[destProp]&&u.typeOf(destObj[destProp])=="array"&&destObj[destProp].length>0)){destObj[destProp]=sourceObj[sourceProp].slice(0);}};function _addToEvent(t_criteo_q,ecm){var temp=[],i,j,_prod;for(i=0;i<u.data.event_list.length;i++){_event=u.data.event_list[i];var g=u.data[_event]=(u.data[_event]||{});g.event=_event;_prod=(u.typeOf(g.item)==="object")?Object.create(g.item):{};u.copy_ecm_array(ecm,"product_id",_prod,"id");u.copy_ecm_array(ecm,"product_unit_price",_prod,"price");u.copy_ecm_array(ecm,"product_quantity",_prod,"quantity");_prod.id=_prod.id||0;switch(_event){case"viewItem":case"viewList":case"viewCategory":case"viewSearchResult":if(g.filters){temp=[];for(j=0;j<g.filters.name.length;j++){temp.push({name:g.filters.name[j],operator:g.filters.operator[j],value:(u.typeOf(g.filters.value[j])==="array"?g.filters.value[j].join(", "):g.filters.value[j])});}
g.filters=temp;}
g.item=g.item||_prod.id;break;case"addToCart":case"viewBasket":case"trackTransaction":temp=[];for(j=0;j<_prod.id.length;j++){temp.push({id:_prod.id[j],price:_prod.price[j],quantity:_prod.quantity[j]});}
g.item=temp;if(_event==="trackTransaction"){g.id=g.id||u.data.transaction_id;g.deduplication=u.data.deduplication}
break;}
t_criteo_q.push(u.clearEmptyKeys(g));}}
u.map={"criteo_partner_id":"account","criteo_site_type":"site_type","criteo_event":"event_list","search_term":"keywords","criteo_product_id":"product_id","criteo_product_price":"product_unit_price","criteo_product_quantity":"product_quantity","logged_in_customer_id":"customer_id","cp.criteo_dedupe":"deduplication","criteo_section":"section","criteo_segment":"user_segment","cp.__adi_rt_DkpyPh8":"test_group","cp.customer_hashed_email_pers":"hashedEmail","analytics_pagename":"section"};u.extend=[function(a,b){try{if(b['logged_in'].toString().toLowerCase()=='TRUE'.toLowerCase()){b['logged_in_customer_id']=b['euci']}}catch(e){utag.DB(e);}},function(a,b,c,d,e,f,g){if(1){d=b['language_country'];if(typeof d=='undefined')return;c=[{'TR:.*':'16648'},{'KR:.*':'126435'},{'IN:.*':'101949'},{'BR:.*':'7688'},{'AU:.*':'113202'},{'NZ:.*':'120988'},{'ID:.*':'117600'},{'PH:.*':'115670'},{'VN:.*':'117599'},{'SG:.*':'116008'},{'MY:.*':'116007'},{'TH:.*':'116009'},{'JP:.*':'10948'},{'ID:.*':'117600'},{'ZA:.*':'121835'},{'IL:.*':'99717'},{'SA:AR':'24605'},{'SA:EN':'24604'},{'MA:FR':'109021'},{'MA:AR':'109033'},{'AE:EN':'24598'},{'AE:AR':'24603'}];var m=false;for(e=0;e<c.length;e++){for(f in utag.loader.GV(c[e])){g=new RegExp(f,'i');if(g.test(d)){b['criteo_partner_id']=c[e][f];m=true};};if(m)break};if(!m)b['criteo_partner_id']='';}},function(a,b,c,d,e,f,g){if(1){d=b['tealium_event'];if(typeof d=='undefined')return;c=[{'^(category_landing_view|search_view|category_view)$':'viewList'},{'^(cart_view)$':'viewBasket'},{'purchase|checkout':'trackTransaction'},{'^(home_view|brand_view)$':'viewHome'},{'^(product_view)$':'viewItem'}];var m=false;for(e=0;e<c.length;e++){for(f in utag.loader.GV(c[e])){g=new RegExp(f,'i');if(g.test(d)){b['criteo_event']=c[e][f];m=true};};if(m)break};if(!m)b['criteo_event']='';}},function(a,b){try{if(1){if(b.tealium_event=='category_landing_view'){if(b.filter_sport=='FOOTBALL'){b.criteo_section='football';}else if(b.filter_sport=='BASKETBALL'){b.criteo_section='basketball';}else if(b.filter_brand=='ORIGINALS'){b.criteo_section='originals';}else if(b.filter_sport=='RUNNING'){b.criteo_section='running';}else if(b.filter_brand=='ADIDAS BY STELLA MCCARTNEY'){b.criteo_section='stella_mccartney';}else if(b.filter_sport=='GOLF'){b.criteo_section='golf';}else if(b.filter_sport=='MICOACH'){b.criteo_section='micoach';}else if(b.filter_sport=='TRAINING'){b.criteo_section='training';}else if(b.filter_sport=='TENNIS'){b.criteo_section='tennis';}else if(b.filter_brand=='ADIDAS NEO'){b.criteo_section='adidasneo';}else if(b.filter_brand=='PORSCHE DESIGN SPORT'){b.criteo_section='porsche_design_sport';}}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){try{b['criteo_site_type']=b.is_mobile&&b.is_mobile=='TRUE'?'m':'d'}catch(e){}}}catch(e){utag.DB(e);}},function(a,b){try{if(1){if(b.criteo_event=='trackTransaction'&&!b.order_id){b.criteo_event='';}
if(!b.criteo_event){return false;}
if(!b.criteo_product_id){if(b.product_id){b.criteo_product_id=b.product_id.slice(0,3);}}
if(typeof(b.criteo_product_id)=='object'){b.criteo_product_price=[];b.criteo_product_quantity=[];for(var i=0;i<b.criteo_product_id.length;i++){if(b.product_quantity&&b.product_quantity[i]){b.criteo_product_quantity.push(b.product_quantity[i]);}
var price;if(b.product_price&&b.product_price[i]){price=b.product_price[i];}else if(b.product_price_vat&&b.product_price_vat[i]){price=b.product_price_vat[i];}else{price='1';}
if(b.country=='PL'||b.country=='CZ'){price=tealiumiq_currency.convert(price,b.currency_code,'EUR');}
b.criteo_product_price.push(price);}
}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:25");utag.DB(b);var c,d,e,f,h,evt=[],_ecm={};u.data={"base_url":"https://dynamic.criteo.com/js/ld/ld.js?a=##account##","account":"978","site_type":(function(){return/iPad/.test(navigator.userAgent)?"t":(/Mobile|iP(hone|od)|Android|BlackBerry|IEMobile|Silk/.test(navigator.userAgent)?"m":"d");}()),"order_id":"","product_id":[],"product_quantity":[],"product_unit_price":[],"event_list":[],"keywords":"","customer_id":"","deduplication":1};var t_criteo_q=[];for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB("send:25:EXTENSIONS");utag.DB(b);c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.map_func(e[f].split("."),u.data,b[d]);}}else{h=d.split(":");if(h.length===2&&b[h[0]]===h[1]){if(u.map[d]){evt=evt.concat(u.map[d].split(","));}}}}
utag.DB("send:25:MAPPINGS");utag.DB(u.data);if(u.data.cusotmer_id&&!u.data.customer_id){u.data.customer_id=u.data.cusotmer_id}
if(!u.data.account){utag.DB(u.id+": Tag not fired: Required attribute account not populated");return;}
u.data.base_url=u.data.base_url.replace("##account##",u.data.account);u.data.order_id=u.data.order_id||b._corder||"";if(u.data.product_id.length===0&&b._cprod!==undefined){u.data.product_id=b._cprod.slice(0);}
if(u.data.product_quantity.length===0&&b._cquan!==undefined){u.data.product_quantity=b._cquan.slice(0);}
if(u.data.product_unit_price.length===0&&b._cprice!==undefined){u.data.product_unit_price=b._cprice.slice(0);}
u.data.transaction_id=u.data.transaction_id||u.data.order_id;_ecm.product_id=u.data.product_id;_ecm.product_unit_price=u.data.product_unit_price;_ecm.product_quantity=u.data.product_quantity;if(!u.isEmpty(u.data.account)){t_criteo_q.push({"event":"setAccount","account":u.prep(u.data.account,false)});}else{utag.DB("error:25:Criteo Account ID Missing");return;}
if(!u.isEmpty(u.data.site_type)){t_criteo_q.push({"event":"setSiteType","type":u.data.site_type});}
if(!u.isEmpty(u.data.email)){t_criteo_q.push({"event":"setEmail","email":u.prep(u.data.email,true)});}
if(!u.isEmpty(u.data.hashedEmail)){t_criteo_q.push({"event":"setHashedEmail","email":u.prep(u.data.hashedEmail,true)});}
if(!u.isEmpty(u.data.retailer_visitor_id)){t_criteo_q.push({"event":"setRetailerVisitorId","id":u.prep(u.data.retailer_visitor_id,true)});}
if(!u.isEmpty(u.data.customer_id)){t_criteo_q.push({"event":"setCustomerId","id":u.prep(u.data.customer_id,true)});}
if(!u.isEmpty(u.data.zip_code)){t_criteo_q.push({"event":"setZipcode","zipcode":u.prep(u.data.zip_code,true)});}
u.data.event_list=u.data.event_list.concat(evt);if(typeof(u.data.event_list)==="string"){u.data.event_list=[u.data.event_list];}
u.data.event_list=u.arrayUnique(u.data.event_list);_addToEvent(t_criteo_q,_ecm);criteo_q.push(t_criteo_q);if(!u.scriptRequested){u.scriptRequested=true;u.loader({"type":"script","src":u.data.base_url,"loc":"script","id":'utag_25'});}
utag.DB("send:25:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("25","adidas.adidasglobal"));}catch(error){utag.DB(error);}
