//tealium universal tag - utag.476 ut4.0.202604290827, Copyright 2026 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<41){u.loader=function(o,a,b,c,l,m){utag.DB(o);a=document;if(o.type=="iframe"){m=a.getElementById(o.id);if(m&&m.tagName=="IFRAME"){b=m;}else{b=a.createElement("iframe");}o.attrs=o.attrs||{};utag.ut.merge(o.attrs,{"height":"1","width":"1","style":"display:none"},0);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";}if(o.id){b.id=o.id;}for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState=="complete"||this.readyState=="loaded"){this.onreadystatechange=null;o.cb();}};}}if(o.type!="img"&&!m){l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}}};}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1,"link":1};u.initialized=false;u.scriptrequested=false;u.queue=[];u.map={"tag_id":"subscription_name"};u.extend=[function(a,b){try{if(1){function push_qm_event(event_name,event_attributes){if(!event_name||typeof event_name!=='string')return;if(typeof window==='undefined')return;window.QuantumMetricData=window.QuantumMetricData||[];window.QuantumMetricData.push({event_name:event_name,attributes:event_attributes||{}});}
function build_products_from_data_layer(data_layer){if(!data_layer||typeof data_layer!=='object')return undefined;if(!Array.isArray(data_layer.product_id)||data_layer.product_id.length===0)return undefined;data_layer.product_price_eur=[];data_layer.product_price_fixed=[];for(var i=0;i<data_layer.product_price.length;i++){var price=parseFloat(data_layer.currency_code=='EUR'?data_layer.product_price[i]:tealiumiq_currency.convert(data_layer.product_price[i],data_layer.currency_code,'EUR'));data_layer.product_price_eur.push((price).toFixed(2));data_layer.product_price_fixed.push(((data_layer.product_price[i])/parseFloat(data_layer.currency_code=='EUR'?1:data_layer.exchange_rate_fixed)).toFixed(2));}
const product_keys=Object.keys(data_layer).filter(key=>key.startsWith('product_'));if(product_keys.length===0)return undefined;const max_length=Math.max(...product_keys.map(key=>Array.isArray(data_layer[key])?data_layer[key].length:0));const ref_length=data_layer.product_id.length;const normalized={};const shared={};product_keys.forEach(key=>{const arr=Array.isArray(data_layer[key])?data_layer[key]:[];if(arr.length===ref_length){normalized[key]=arr;}else if(arr.length===1){normalized[key]=Array(ref_length).fill(arr[0]);}else if(arr.length>ref_length){shared[key]=arr;normalized[key]=Array(ref_length).fill(null);}else{normalized[key]=arr.concat(Array(ref_length-arr.length).fill(null));}});return Array.from({length:ref_length},(_,i)=>{const product={};product_keys.forEach(key=>{const prop=key.replace(/^product_/,'');if(shared[key]){product[prop]=(i===0)?shared[key]:null;}else{const value=normalized[key][i];product[prop]=value!==undefined?value:null;}});return product;});}
function safe_string(value){return typeof value==='string'?value:null;}
function safe_boolean(value){return!!value;}
function safe_number(value){return typeof value==='number'?value:null;}
function get_ga_session_id(data_layer){if(!data_layer||typeof data_layer['cp._ga']!=='string')return null;return data_layer['cp._ga'].replace('GA1.1.','');}
function get_qm_session_id(){if(typeof window==='undefined')return null;let qm_session_id=null;if(window.QuantumMetricAPI&&typeof window.QuantumMetricAPI.getSessionID==='function'){try{qm_session_id=window.QuantumMetricAPI.getSessionID();if(qm_session_id){qm_session_id=qm_session_id.toString();if(typeof window.sessionStorage!=='undefined'){window.sessionStorage.setItem('qmSessionID',qm_session_id);}}}catch(e){}}
if(!qm_session_id&&typeof window.sessionStorage!=='undefined'){qm_session_id=window.sessionStorage.getItem('qmSessionID');}
return qm_session_id?qm_session_id.toString():null;}
function build_error_info(data_layer){if(!data_layer||!data_layer.tealium_event)return null;if(data_layer.tealium_event==='error_page'){return{error_category:'error_page',error_code:safe_string(data_layer.page_name)};}
if(data_layer.tealium_event==='form_error'){const form_error=data_layer.form_error;let error_message=[];if(Array.isArray(form_error)){error_message=form_error;}else if(typeof form_error==='string'&&form_error.length>0){error_message=[form_error];}
return{error_category:'form_error',form_name:safe_string(data_layer.form_name),error_message:error_message};}
if(data_layer.tealium_event==='add_to_cart_error'){const form_error=data_layer.form_error;let error_message=[];if(Array.isArray(form_error)){error_message=form_error;}else if(typeof form_error==='string'&&form_error.length>0){error_message=[form_error];}
return{error_category:'add_to_cart_error',error_message:error_message};}
return null;}
function build_search_data(data_layer){if(!data_layer||data_layer.tealium_event!=='search_view')return null;let search_term=null;if(data_layer['qp.q']&&typeof data_layer['qp.q']==='string'){try{search_term=decodeURIComponent(data_layer['qp.q']);}catch(e){search_term=data_layer['qp.q'];}}
return{results_count:safe_string(data_layer.search_results),search_term:search_term,search_type:safe_string(data_layer.search_type)};}
function build_geo_data(data_layer){const country=(safe_string(data_layer.country)||'').replace(/UK/g,'GB');const language=(safe_string(data_layer.language)||'').toLowerCase();return{country:country,currency:safe_string(data_layer.currency_code),geo_country:safe_string(data_layer.geo_country),language:language,locale:`${language}_${country}`};}
function build_consent_data(data_layer){const has_full_consent=safe_boolean(data_layer.functional_allowed)&&safe_boolean(data_layer.marketing_allowed);return{consent_model:has_full_consent?'opt-in':'opt-out',consent_necessary:true,consent_functional:safe_boolean(data_layer.functional_allowed),consent_marketing:safe_boolean(data_layer.marketing_allowed),do_not_track:(typeof navigator!=='undefined')?navigator.doNotTrack:null};}
function build_integrations_data(data_layer){return{adobe_visitor_id:safe_string(data_layer.adobe_visitor_id),ga_session_id:get_ga_session_id(data_layer),instana_session_id:safe_string(data_layer.instana_session_id),qm_session_id:get_qm_session_id()};}
function build_page_data(data_layer){return{page_name:safe_string(data_layer.analytics_pagename),page_type:safe_string(data_layer.page_type),url:(typeof document!=='undefined'&&document.location)?document.location.href:null,path:document.location.pathname||null,domain:document.location.hostname||null,referrer:document.referrer||null,query_params:document.location.search||null,hash:document.location.hash||null,active_experiments:b.active_experiments?b.active_experiments.split('|'):null};}
function build_cart_data(data_layer){if(!data_layer||typeof data_layer!=='object')return null;const cart_id=safe_string(data_layer.cart_id);const rawTotal=data_layer.basket_product_total??data_layer.cart_total??data_layer.basket_total;let cart_total=null;if(rawTotal!==undefined&&rawTotal!==null){if(typeof rawTotal==='number'&&Number.isFinite(rawTotal)){cart_total=rawTotal.toString();}else if(typeof rawTotal==='string'&&rawTotal.trim()!==''){cart_total=rawTotal;}
if(b.currency!='EUR'){cart_total=cart_total/parseFloat(b.exchange_rate_fixed);cart_total=cart_total.toFixed(2);}}
return{cart_id:cart_id,cart_total:cart_total};}
function build_user_data(data_layer){return{user_status:safe_string(data_layer.customer_status),user_id:safe_string(data_layer.euci),};}
function build_environment_data(data_layer){return{environment:data_layer.environment,version:data_layer.version_info};}
function build_promotion_info(data_layer){return{promo_code:safe_string(data_layer.promo_code)};}
function build_marketing_data(data_layer){let medium=null,source=null,campaign=null;const mmc=data_layer['qp.mmc'];const mmc_source=data_layer.mmc_source;const cm_mmc=data_layer['qp.cm_mmc'];const cm_mmc2=data_layer['qp.cm_mmc2'];if(typeof mmc==='string'&&mmc_source!=="cm_mmc"){let mmc_separator=mmc.includes("-_-")?"-_-":"_";const mmc_split=mmc.split(mmc_separator);let mmc_dict={};const origin_fields=["adichannel","hub","country"];let common_fields=["channel_group","placement_type","media_subchannel","funnel","activity_type","vendor","tactic","campaign","category","test","yymm","luminaid","market_spec_field_1","market_spec_field_2","market_spec_field_3"];for(let i=0;i<origin_fields.length;i++){mmc_dict[origin_fields[i]]=mmc_split[i];}
let adi_channel_lower=(mmc_dict.adichannel||"").toLowerCase();if(adi_channel_lower==="adisem"){common_fields[common_fields.indexOf("campaign")]="targeting";common_fields=common_fields.filter(f=>!["yymm","luminaid"].includes(f));}
const all_fields=origin_fields.concat(common_fields);for(let i=0;i<all_fields.length;i++){mmc_dict[all_fields[i]]=mmc_split[i];}
medium=mmc_dict.adichannel?mmc_dict.adichannel.replace(/^(adie?)/gi,""):null;source=mmc_dict.vendor||null;campaign=mmc||null;}
else if(typeof cm_mmc==='string'&&mmc_source!=="mmc"){const cm_split=cm_mmc.split('-_-');const medium_source=(cm_split[0]||'').replace(/^(adie?)/gi,'').split('_');medium=medium_source[0]||null;source=medium_source[1]||null;campaign=cm_mmc2||cm_split[1]||null;}
else{medium=data_layer.utm_medium||null;source=data_layer.utm_source||null;campaign=data_layer.utm_campaign||null;}
return{medium,source,campaign};}
function build_filters(data_layer){if(!data_layer||!Array.isArray(data_layer.filters_applied)||data_layer.filters_applied.length===0)return null;const filters_applied=[];const filter_values={};data_layer.filters_applied.forEach(item=>{if(typeof item!=='string')return;const[raw_key,...raw_values]=item.split(':');if(!raw_key||raw_values.length===0)return;const key=raw_key.trim().toLowerCase().replace(/[^a-z0-9]/g,'_');filters_applied.push(raw_key.trim().toUpperCase());const values=raw_values.join(':').split(',').map(v=>v.trim()).filter(Boolean);filter_values[`filter_${key}`]=values;});return{filters_applied,...filter_values};}
function build_payment_info(data_layer){if(!data_layer)return null;if(data_layer.customer_payment_type){const payment=data_layer.customer_payment_type;return{payment_type:payment};}
const raw=safe_string(data_layer.event_name);if(!raw)return null;const parts=raw.split(':');const payment=parts.length>1?parts[1].trim():null;return{payment_type:payment&&payment.length?payment:null};}
function build_delivery_info(data_layer){if(!data_layer||typeof data_layer!=='object')return null;const product_delivery_details=data_layer.product_delivery_details!==undefined?data_layer.product_delivery_details:null;const delivery_method=safe_string(data_layer.delivery_method);return{product_delivery_details,delivery_method};}
function build_purchase_info(data_layer){if(!data_layer||typeof data_layer!=='object')return null;const order_id=safe_string(data_layer.order_id);let purchase_value=null;const rawValue=data_layer.order_subtotal;if(typeof rawValue==='number'&&Number.isFinite(rawValue)){purchase_value=rawValue;}else if(typeof rawValue==='string'&&rawValue.trim()!==''){const cleaned=rawValue.replace(/[^0-9.\-]+/g,'');const n=Number(cleaned);purchase_value=Number.isFinite(n)?n:null;}
const purchase_value_eur=b.order_subtotal_eur;let total_quantity=null;const rawQty=data_layer.product_quantity_total??data_layer.quantity??data_layer.total_quantity;if(typeof rawQty==='number'&&Number.isFinite(rawQty)){total_quantity=rawQty;}else if(typeof rawQty==='string'&&rawQty.trim()!==''){const q=Number(rawQty.replace(/[^0-9.\-]+/g,''));total_quantity=Number.isFinite(q)?q:null;}
return{order_id,purchase_value,total_quantity,purchase_value_eur,};}
function build_event_data(data_layer){if(!data_layer||typeof data_layer!=='object')return null;let event_data={consent_data:build_consent_data(data_layer),geo_data:build_geo_data(data_layer),integrations_data:build_integrations_data(data_layer),page_data:build_page_data(data_layer),user_data:build_user_data(data_layer),cart_data:build_cart_data(data_layer),environment_data:build_environment_data(data_layer)};const products=build_products_from_data_layer(data_layer);if(products){event_data.products=products;}
const error_info=build_error_info(data_layer);if(error_info){event_data.error_info=error_info;}
const search_data=build_search_data(data_layer);if(search_data){event_data.search_data=search_data;}
const filters=build_filters(data_layer);if(filters){event_data.filters=filters;}
const marketing_data=build_marketing_data(data_layer);if(filters){event_data.marketing_data=marketing_data;}
if(data_layer&&(data_layer.tealium_event==='promo_code_attempt'||data_layer.tealium_event==='promo_code_success')){const promotion_info=build_promotion_info(data_layer);if(promotion_info){event_data.promotion_info=promotion_info;}}
if(data_layer&&(data_layer.tealium_event==='select_payment_method'||data_layer.tealium_event==='purchase')){const payment_info=build_payment_info(data_layer);if(payment_info){event_data.payment_info=payment_info;}}
if(data_layer&&(data_layer.tealium_event==='select_delivery_method'||data_layer.tealium_event==='purchase')){const delivery_info=build_delivery_info(data_layer);if(delivery_info){event_data.delivery_info=delivery_info;}}
if(data_layer&&data_layer.tealium_event==='purchase'){const purchase_info=build_purchase_info(data_layer);if(purchase_info){event_data.purchase_info=purchase_info;}}
return event_data;}
const allowed_events=['add_to_cart_error','cart_add','cart_remove','cart_view','category_view','checkout_review_pay','error_page','form_error','product_click','product_view','promo_code_attempt','promo_code_success','purchase','search_view','search','select_delivery_method','select_payment_method','wishlist_add','wishlist_remove'];if(b&&(allowed_events.includes(b.tealium_event)||a=='view')){const event_name=safe_string(b.tealium_event)||'page_view';const event_data=build_event_data(b);if(event_data){push_qm_event(event_name,event_data);}}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){u.quantum_metric_handler=function(){function calculateCartValue(){if(b.product_quantity&&b.product_price){var cart_value=0;for(var i=0;i<b.product_quantity.length;i++){cart_value+=parseInt(b.product_quantity[i])*parseFloat(b.product_price[i]);}}
if(cart_value&&b.currency_code!="EUR"){cart_value=cart_value/parseFloat(b.exchange_rate_fixed);}
if(cart_value){return parseInt(cart_value.toFixed(2)*100);}}
var qm_send_event_dict={product_view:[{id:6,val:0,flags:b.product_id},{id:90,val:0,flags:b.product_status}],home_view:[{id:107,val:0}],purchase:[{id:33,val:1,flags:calculateCartValue()},{id:55,val:0,flags:b.customer_payment_type}],category_view:[{id:8,val:0,flags:b.analytics_pagename}],cart_add:[{id:7,val:0}],cart_view:[{id:({"CART":11,"EMPTY CART":84,"MINICART OVERLAY":9})[b.page_name],val:0,flags:"",cond:["CART","EMPTY CART","MINICART OVERLAY"].indexOf(b.page_name)!==-1},{id:10,val:0,flags:calculateCartValue(),cond:b.page_name==="CART"}],checkout_shipping:[{id:15,val:0}],checkout_payment:[{id:103,val:0}],checkout_delivery:[{id:69,val:0}],checkout_review_pay:[{id:14,val:0}],user_register_start:[{id:64,val:0}],user_register:[{id:65,val:0}],wishlist_add:[{id:229,val:0}]}
var send_events=qm_send_event_dict[b.tealium_event];if(send_events){send_events.forEach((send_event)=>{if(Object.keys(send_event).indexOf("cond")===-1||send_event.cond){QuantumMetricAPI.sendEvent(send_event.id,send_event.val,send_event.flags||"");}});}
if(a=="view"){QuantumMetricAPI.sendEvent(56,0,b.page_type);QuantumMetricAPI.sendEvent(49,0,b.customer_status);QuantumMetricAPI.sendEvent(231,0,b.analytics_pagename);if(b.search_term){var search_term=b.search_term.split("|")[0];QuantumMetricAPI.sendEvent(17,0,search_term);}
if(b.analytics_pagename=="CHECKOUT|REVIEW AND PAY"){QuantumMetricAPI.sendEvent(14,0,"")}
if(b.analytics_pagename&&b.analytics_pagename.indexOf('CLP')>-1){QuantumMetricAPI.sendEvent(108,0,'');}
if(b.analytics_pagename&&b.analytics_pagename.indexOf("GLP")>-1){QuantumMetricAPI.sendEvent(109,0,"");}
if(b.search_type){if(b.page_type=="SEARCH"){QuantumMetricAPI.sendEvent(97,0,"ORGANIC SEARCH");}else{QuantumMetricAPI.sendEvent(97,0,"SEARCH REDIRECT "+b.page_type);}}
if(b.product_excluded_from_promotions){QuantumMetricAPI.sendEvent(249,0,b.product_excluded_from_promotions);}}else if(a=="link"){if(b.event_name&&b.event_name.indexOf('DELIVERY OPTIONS RENDERED')>-1){QuantumMetricAPI.sendEvent(245,0,b.delivery_methods_available);}
if(b.event_name=="PAYPAL CHECKOUT"||(b.event_name=="PAYPAL"&&b.customer_payment_type=="PAYPAL")){var event_id={"SHOPPING CART|CART":13,"CHECKOUT|PAYMENT":102}
QuantumMetricAPI.sendEvent(event_id[b.analytics_pagename],0,"");}
if(b.event_category=="FORM ERRORS"&&b.form_error&&b.form_error.length>0&&b.form_error[0].indexOf("DELIVERY.DELIVERY BUTTON IRRESPONSIVE")>-1){QuantumMetricAPI.sendEvent(100,0,"");}
if(b.tool_name=='COMPARISON TOOL'&&b.tool_state=='EXPOSED'){QuantumMetricAPI.sendEvent(232,0,"");}
if(b.event_category&&b.event_name){const element_name=[b.event_category,b.event_name].join('|');QuantumMetricAPI.sendEvent(247,0,element_name);}}
if(b.event_category=="FORM ERRORS"&&b.form_error&&b.form_error.length>0&&b.form_name){b.form_error=Array.isArray(b.form_error)?b.form_error:[b.form_error];for(let index=0;index<b.form_error.length;index++){QuantumMetricAPI.sendEvent(222,0,b.form_error[index]);}
QuantumMetricAPI.sendEvent(223,0,b.form_name);}
if(b.active_experiments&&b.active_experiments.split&&b.active_experiments.length>0){b.active_experiments=b.active_experiments.split("|");for(var i=0;i<b.active_experiments.length;i++){QuantumMetricAPI.sendEvent(1,0,b.active_experiments[i]);}}
if(b.product_prime_status&&b.product_prime_status.length>0){QuantumMetricAPI.sendEvent(244,0,b.product_prime_status);}
if(b.tealium_event&&b.tealium_event!='link'&&b.tealium_event!='page_view'){QuantumMetricAPI.sendEvent(246,0,b.tealium_event);}}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){try{b['tag_id']='adidasgroup'+(b.environment=='PRODUCTION'?'':'-test')}catch(e){}}}catch(e){utag.DB(e);}}];u.loader_cb=function(a,b,c){utag.DB("send:476:CALLBACK");u.initialized=true;if(window.QuantumMetricAPI){u.quantum_metric_handler();}
utag.DB("send:476:CALLBACK:COMPLETE");};u.callBack=function(){var data={};while(data=u.queue.shift()){u.data=data.data;u.loader_cb(data.a,data.b,data.c);}};u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:476");utag.DB(b);var c,d,e,f;u.data={"qsp_delim":"&","kvp_delim":"=","subscription_name":"","tealium_account":"","tealium_profile":"","send_replay_url":"false","ts":"","base_url":"//cdn.quantummetric.com/qscripts/quantum-##utag_subscription_name##.js","dc_base_url":"https://collect.tealiumiq.com/vdata/i.gif?","replay_url":"https://##utag_subscription_name##.quantummetric.com/#/users/search?","autoreplay":"true","replaysecond":"-20","qmUserCookie":"","qmSessionCookie":"","custom":{}};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB("send:476:EXTENSIONS");utag.DB(b);c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(u.data.hasOwnProperty(e[f])){u.data[e[f]]=b[d];}else{u.data.custom[e[f]]=b[d];}}}}
utag.DB("send:476:MAPPINGS");utag.DB(u.data);if(!u.data.subscription_name){utag.DB(u.id+": Tag not fired: Required attribute subscription_name not populated");return;}
u.data.ts=u.data.ts||"30days";u.data.send_replay_url=(u.data.send_replay_url===true||u.data.send_replay_url.toLowerCase()==="true")?true:false;u.data.base_url=u.data.base_url.replace("##utag_subscription_name##",u.data.subscription_name);if(u.initialized&&!u.replay_url_sent){u.loader_cb(a,b,c);}else{u.queue.push({"data":u.data,"a":a,"b":b,"c":c});if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":"script","src":u.data.base_url,"cb":u.callBack,"loc":"script","id":"utag_476","attrs":{}});}}
utag.DB("send:476:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("476","adidas.adidasglobal"));}catch(error){utag.DB(error);}
